name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" # execute every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # Update to a version that supports Node.js 20
        with:
          ref: v2.4.0

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Use a palette that supports custom colors, if available
          outputs: dist/snake.svg?color=9370db

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Update to a version that supports Node.js 20
        if: github.event_name != 'schedule' || contains(github.event.head_commit.message, 'force-run')
